export const menu = [
  {
    id: 0,
    categoryName: 'Hot Coffee',
    slug: 'hotcoffee',
    itemsList:
      [
        {
          id: 0,
          img: '/images/hotcoffee/spanishlatte.jpeg',
          itemName: 'Spanish Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '26',
        },
        {
          id: 1,
          img: '/images/hotcoffee/americano.webp',
          itemName: 'Americano',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '16',
        },
        {
          id: 2,
          img: '/images/hotcoffee/Cafe Latte.webp',
          itemName: 'Coffe Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '24',
        },
        {
          id: 3,
          img: '/images/hotcoffee/Flat White.webp',
          itemName: 'Flat White',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '23',
        },
        {
          id: 4,
          img: '/images/hotcoffee/espresso.webp',
          itemName: 'Espresso',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '16',
        },
        {
          id: 5,
          img: '/images/hotcoffee/cortado.webp',
          itemName: 'Cortado',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '22',
        },
        {
          id: 6,
          img: '/images/hotcoffee/chemex.jpeg',
          itemName: 'Chemex',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '27',
        },
        {
          id: 7,
          img: '/images/placeholder.png',
          itemName: 'French Press',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '26',
        },
        {
          id: 8,
          img: '/images/placeholder.png',
          itemName: 'Pistachio Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '30',
        },
        {
          id: 9,
          img: '/images/hotcoffee/caramel latte.webp',
          itemName: 'Caramel Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '26',
        },
        {
          id: 10,
          img: '/images/hotcoffee/Affogato.webp',
          itemName: 'Afoqatto',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '28',
        },
        {
          id: 11,
          img: '/images/placeholder.png',
          itemName: 'Hot Chocolate',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '25',
        },
        {
          id: 12,
          img: '/images/hotcoffee/v60.jpeg',
          itemName: 'V60',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '27',
        },
        {
          id: 13,
          img: '/images/placeholder.png',
          itemName: 'Single Espresso',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '14',
        },
      ],
  },

  {
    id: 1,
    categoryName: 'Iced Coffee',
    slug: 'icedcoffee',
    itemsList:
      [
        {
          id: 0,
          img: '/images/icedcoffee/icedv60.jpeg',
          itemName: 'Iced V60',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '26',
        },
        {
          id: 1,
          img: '/images/icedcoffee/Ice Americano.webp',
          itemName: 'Iced Americano',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '22',
        },
        {
          id: 2,
          img: '/images/icedcoffee/Ice Latte.webp',
          itemName: 'Iced Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '24',
        },
        {
          id: 3,
          img: '/images/icedcoffee/Ice Cappucino.webp',
          itemName: 'Iced Cappuccino',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '24',
        },
        {
          id: 4,
          img: '/images/icedcoffee/Iced Flat White.webp',
          itemName: 'Iced Flat White',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '23',
        },
        {
          id: 5,
          img: '/images/icedcoffee/Ice Spanish Latte.webp',
          itemName: 'Iced Spanish Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '26',
        },
        {
          id: 6,
          img: '/images/icedcoffee/Ice Matcha Latte.webp',
          itemName: 'Iced Mocha Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '24',
        },
        {
          id: 7,
          img: '/images/placeholder.png',
          itemName: 'Iced Pistachio Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '30',
        },
        {
          id: 8,
          img: '/images/icedcoffee/signature latte.webp',
          itemName: 'Signature Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '28',
        },
        {
          id: 9,
          img: '/images/icedcoffee/Ice Matcha Latte.webp',
          itemName: 'Iced Matcha Latte',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '30',
        },
        {
          id: 10,
          img: '/images/placeholder.png',
          itemName: 'My Corner Blend Cold Brew',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '28',
        },
        {
          id: 11,
          img: '/images/icedcoffee/icedchemex.jpeg',
          itemName: 'Iced Chemex',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '27',
        },
        {
          id: 12,
          img: '/images/placeholder.png',
          itemName: 'Iced Chocolate',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '26',
        },
      ],
  },

  {
    id: 2,
    categoryName: 'Shakes',
    slug: 'shakes',
    itemsList:
      [
        {
          id: 0,
          img: '/images/placeholder.png',
          itemName: 'Strawberry Milkshake',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '22',
        },
        {
          id: 1,
          img: '/images/placeholder.png',
          itemName: 'Chocolate milkshake',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '25',
        },
        {
          id: 2,
          img: '/images/placeholder.png',
          itemName: 'Blue Velvet',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '25',
        },
        {
          id: 3,
          img: '/images/placeholder.png',
          itemName: 'White Chocolate Chip',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '25',
        },
        {
          id: 4,
          img: '/images/placeholder.png',
          itemName: 'Coffe Caramel Frappe',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '28',
        },
        {
          id: 5,
          img: '/images/placeholder.png',
          itemName: 'Mocha Frappe',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '28',
        },
        {
          id: 6,
          img: '/images/placeholder.png',
          itemName: 'Chocolate Frappe',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '28',
        },
      ],
  },

  {
    id: 3,
    categoryName: 'Hot Tea',
    slug: 'hottea',
    itemsList:
      [
        {
          id: 0,
          img: '/images/placeholder.png',
          itemName: 'Green Tea',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '20',
        },
        {
          id: 1,
          img: '/images/placeholder.png',
          itemName: 'Red Tea',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '20',
        },
        {
          id: 2,
          img: '/images/placeholder.png',
          itemName: 'Matcha Tea',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '30',
        },
      ],
  },

  {
    id: 4,
    categoryName: 'Dessert',
    slug: 'dessert',
    itemsList:
      [
        {
          id: 0,
          img: '/images/dessert/tiramishu glass cake.webp',
          itemName: 'Tiramisú Glass Cake',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '40',
        },
        {
          id: 0,
          img: '/images/dessert/warm cookie skillet.webp',
          itemName: 'Warm Cookie Skillet',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '45',
        },
        {
          id: 0,
          img: '/images/dessert/sticky dates bread.webp',
          itemName: 'Sticky Dates Bread',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '40',
        },
        {
          id: 0,
          img: '/images/dessert/lime lava cake.webp',
          itemName: 'Lime Lava Cake',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '35',
        },
        {
          id: 0,
          img: '/images/dessert/strawberry mont blanc tart.webp',
          itemName: 'Strawberry Mont Blanc Tart',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '37',
        },
        {
          id: 0,
          img: '/images/dessert/molten lava dulce de leche tahina.webp',
          itemName: 'Molten Lava Dulce De Leche Tahina',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '32',
        },
        {
          id: 0,
          img: '/images/dessert/french toast with caramel.webp',
          itemName: 'French Toast with Caramell',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '45',
        },
      ],
  },

  {
    id: 5,
    categoryName: 'Appetizers',
    slug: 'appetizers',
    itemsList:
      [
        {
          id: 0,
          img: '/images/appetizer/egg benedict.webp',
          itemName: 'Egg Benedict',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '45',
        },
        {
          id: 0,
          img: '/images/appetizer/crock madam.webp',
          itemName: 'Crock Madam',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '50',
        },
        {
          id: 0,
          img: '/images/appetizer/chicken burger.webp',
          itemName: 'Chicken Burger',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '45',
        },
        {
          id: 0,
          img: '/images/appetizer/Beef Burger.webp',
          itemName: 'Beef Burger',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '55',
        },
        {
          id: 0,
          img: '/images/appetizer/helloumi cheese.webp',
          itemName: 'Halloumi',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '35',
        },
        {
          id: 0,
          img: '/images/appetizer/mac and cheese.webp',
          itemName: 'Mac and Cheese',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '45',
        },
        {
          id: 0,
          img: '/images/appetizer/apple salad.webp',
          itemName: 'Apple Salad',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '42',
        },
        {
          id: 0,
          img: '/images/appetizer/avocado salad.webp',
          itemName: 'Avocado Salad',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '48',
        },
        {
          id: 0,
          img: '/images/appetizer/ceasar Salad.webp',
          itemName: 'ceasar salad',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '45',
        },
        {
          id: 0,
          img: '/images/appetizer/scrambled with mushroom.webp',
          itemName: 'Scrambled with Mushroom',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '52',
        },
        {
          id: 0,
          img: '/images/appetizer/chicken wrap sand.webp',
          itemName: 'Wrap Chicken Sandwich',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '32',
        },
      ],
  },

  {
    id: 6,
    categoryName: 'Water',
    slug: 'water',
    itemsList:
      [
        {
          id: 0,
          img: '/images/water/pana250.jpeg',
          itemName: 'Acqua pana 250ml',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '12',
        },
        {
          id: 0,
          img: '/images/water/sparkling.jpeg',
          itemName: 'Sparkling Water',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '15',
        },
        {
          id: 0,
          img: '/images/water/pana500.jpeg',
          itemName: 'Acqua pana 500ml',
          itemDescription: 'lorem ipsum etxt dummy dolar sit.',
          price: '20',
        },
      ],
  },
]
